name: Build & Commit Resume

on:
  push:
    branches: [ deploy ]
    paths:
      - 'kali.json'
      - 'resume_template.html.j2'
      - 'build_resume.py'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build resume HTML
        run: python build_resume.py --json1 kali.json

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(resume): auto-build from JSON"
          file_pattern: "resume/*.html"
